task(3200371080): feeder gateway - deprecate v1 methods
starkware-libs/starkex-js pull request #28
Opened 2022-09-07 18:53 UTC by danielgluskin-starkware

### Description of the Changes

Added a `deprecated` prefix and use V1 for deprecated methods.
Added a messages const.

Solves #[3200371080](https://starkware.monday.com/boards/2847512260/pulses/3200371080)

---

### Checklist

- [ ] New unit / functional tests have been added (whenever applicable).
- [ ] Docs have been updated (whenever relevant).
- [X] PR title is follow the [Conventional Commits](https://www.conventionalcommits.org/) convention: `<type>[optional scope]: <description>`, e.g: `fix: prevent racing of requests`

2022-09-08 05:43 UTC, dan-ziv requested changes

2022-09-08 05:43 UTC, dan-ziv commented on src/utils/messages.ts
> +const MESSAGES = {
Our code convention for enum-like consts is: `PascalCase.SCREAMING_SNAKE_CASE` so please rename to `Messages`.

2022-09-08 05:43 UTC, dan-ziv commented on src/utils/messages.ts
> +  DEPRECATION_MESSAGE:
I would call it only `DEPRECATION`  (since this is nested under `Messages` already) or `DEPRECATED_FUNCTION`.
`Messages.DEPRECATED_FUNCTION`

2022-09-08 06:35 UTC, dan-ziv approved these changes, later dismissed

2022-09-08 08:29 UTC, dan-ziv commented
@danielgluskin-starkware please add in the README file an example on how to call deprecated function and what this does behind the scenes (i.e. remove the `/v2` prefix from the path).

2022-09-08 10:30 UTC, danielgluskin-starkware commented
> @danielgluskin-starkware please add in the README file an example on how to call deprecated function and what this does behind the scenes (i.e. remove the `/v2` prefix from the path).

added. Please approve if all good. @dan-ziv

2022-09-08 10:33 UTC, dan-ziv approved these changes

2022-09-08 10:51 UTC, merged

2022-09-08 12:16 UTC, dan-ziv commented
:tada: This PR is included in version 0.1.0-dev.7 :tada:

The release is available on [GitHub release](https://github.com/starkware-libs/starkex-js/releases/tag/v0.1.0-dev.7)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-09-18 17:12 UTC, dan-ziv commented
:tada: This PR is included in version 0.1.0 :tada:

The release is available on [GitHub release](https://github.com/starkware-libs/starkex-js/releases/tag/v0.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: